//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleflex.Email.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailProcess()
        {
            this.EmailProcessAttachments = new HashSet<EmailProcessAttachment>();
        }
    
        public long EmailProcessKey { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string CcAddress { get; set; }
        public string BccAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public Nullable<System.DateTimeOffset> FutureSendDate { get; set; }
        public Nullable<System.DateTimeOffset> SentDate { get; set; }
        public bool IsError { get; set; }
        public Nullable<System.DateTimeOffset> ErrorDate { get; set; }
        public string ErrorMessage { get; set; }
        public bool IsProcessing { get; set; }
        public Nullable<System.DateTimeOffset> ProcessingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailProcessAttachment> EmailProcessAttachments { get; set; }
    }
}
