//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleflex.Security.Storage.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleRole
    {
        public long RoleRoleKey { get; set; }
        public System.Guid ParentRoleKey { get; set; }
        public System.Guid ChildRoleKey { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.DateTimeOffset> StartDate { get; set; }
        public Nullable<System.DateTimeOffset> EndDate { get; set; }
        public string Comment { get; set; }
        public string ExtraData { get; set; }
        public Nullable<System.Guid> ModuleKey { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
