//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleflex.Versioning.Storage.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public System.Guid ModuleKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int VersionMajor { get; set; }
        public int VersionMinor { get; set; }
        public int VersionBuild { get; set; }
        public int VersionRevision { get; set; }
        public string ExtraData { get; set; }
    }
}
