//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eleflex.Logging.Storage.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogKey { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public string Message { get; set; }
        public bool IsError { get; set; }
        public string Severity { get; set; }
        public string Application { get; set; }
        public string Server { get; set; }
        public string ExtraData { get; set; }
        public string Source { get; set; }
        public string Exception { get; set; }
    }
}
